### ISSUE TITLE
TypeError: object of type 'ResNet' has no len()

### ISSUE THREAD

**Issue by nam-dinh-codes** [Rahul0128/Visualizing-Filters-and-Feature-Maps-in-Convolutional-Neural-Networks-using-PyTorch#1]
Hi,

I tried to run this code on Google Colab on got the error: "TypeError: object of type 'ResNet' has no len()" on line 50 of the extractor.py

I had to add: "resnet = list(resnet.children())[:-1]" after line 13 in Visualizer.py to solve the problem
I don't know how to make a request so I write it here just in case someone has the same problem

**Comment by Rahul0128** [comment]
Hey, 

Sorry for replying so late. I will look into the error and get back to you

**Comment by Ashborn-SM** [comment]
> Hi,
> 
> I tried to run this code on Google Colab on got the error: "TypeError: object of type 'ResNet' has no len()" on line 50 of the extractor.py
> 
> I had to add: "resnet = list(resnet.children())[:-1]" after line 13 in Visualizer.py to solve the problem
> I don't know how to make a request so I write it here just in case someone has the same problem

Yes, i missed `resnet = list(resnet.children())` in the program, i've changed it.
I'm sorry for replying so late.
